name = "tempik"
main = "src/index.ts"
compatibility_date = "2025-06-01"

workers_dev = false

[[d1_databases]]
binding = "DB"
database_name = "tempik-db"
database_id = "0e9fde2a-118b-45a2-b88d-7eff1fb6dc9a"

[email]
action = "process"

# [[routes]]
# pattern = "tempik.haerubirru.my.id"
# custom_domain = true

[vars]
APP_NAME = "Tempik"
MAIL_DOMAIN = "haerubirru.my.id, biruruang.my.id, berbirru.com"
VIP_DOMAINS = "berbirru.com"
WEB_HOST = "tempik.haerubirru.my.id"

[assets]
directory = "./src/web"

[observability]
enabled = true
